# Generated by Django 5.2 on 2025-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='feedback_text',
            field=models.TextField(blank=True),
        ),
    ]
