# Generated by Django 5.2 on 2025-04-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='pass_hash',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='pub_key',
            new_name='public_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='high_score',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
