# Generated by Django 5.2 on 2025-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_pass_hash_credential_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='high_score',
            field=models.IntegerField(default=0),
        ),
    ]
